api_platform:
    title: The Feed API
    version: 1.0.0
    defaults:
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        formats:
            jsonld: ['application/ld+json']
            json: ['application/json']
        pagination_items_per_page: 30 # Pour changer le nombre de ressources renvoyées si la pagination est activée
        pagination_enabled: false # Active ou désactive la pagination