
# Dans config/packages/gesdinet_jwt_refresh_token.yaml
gesdinet_jwt_refresh_token:
    # Classe représentant le token de rafraîchissement (option déjà paramétrée, par défaut)
    refresh_token_class: App\Entity\RefreshToken
    # Pour que la durée de vie du token de rafraîchissement soit réinitialisée (à son maximum) après chaque utilisation
    ttl_update: true
    # Cette option permet de stocker le token de rafraîchissement dans un cookie (sécurisé, comme pour le JWT) au lieu de le renvoyer dans le corps de la réponse.
    cookie:
        enabled: true

    # Le firewall (section définie dans security.yaml) paramétrant notre système de déconnexion / d'invalidation de token.
    logout_firewall: main
